spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://120.48.78.129:3307/cube?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.ymusic.domain